# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    allow:
      - dependency-type: "all"
    schedule:
      interval: daily
      day: 'tuesday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    reviewers:
      - 'kjanat'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows/'
    allow:
      - dependency-type: "all"
    schedule:
      interval: daily
      day: 'tuesday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'github-actions'
      include: 'scope'
    reviewers:
      - 'kjanat'
    groups:
      github-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'docker'
    directories:
      - '/'
      - '/.github/workflows/docker'
    allow:
      - dependency-type: "all"
    schedule:
      interval: daily
      day: 'tuesday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    reviewers:
      - 'kjanat'
    groups:
      docker-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'docker-compose'
    directories:
      - '/'
      - '/.github/workflows/docker'
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "all"
    schedule:
      interval: daily
      day: 'tuesday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    reviewers:
      - 'kjanat'
    groups:
      docker-dependencies:
        patterns:
          - '*'
