version: "2"

linters:
  exclusions:
    # Which file paths to exclude: they will be analyzed, but issues from them won't be reported.
    # "/" will be replaced by the current OS file path separator to properly work on Windows.
    # Default: []
    paths:
      - docs
      - vendor
      - .github
      - .git
      - .idea
      - .vscode
      - scripts
      - migrations

formatters:
  exclusions:
    # Which file paths to exclude.
    # Default: []
    paths:
      - docs
      - vendor
      - .github
      - .git
      - .idea
      - .vscode
      - scripts
      - migrations
