# For more information on configuration options, see:
# https://golangci-lint.run/usage/configuration/

# Configuration file version
# Required in recent versions of golangci-lint
version: 2

# Options for analysis running
run:
  # Timeout for analysis, e.g. 30s, 5m
  # Default: 1m
  timeout: 5m
  
  # Exit code when at least one issue was found
  # Default: 1
  issues-exit-code: 1
  
  # Allow multiple parallel golangci-lint instances running.
  # Useful for CI pipelines.
  allow-parallel-runners: true

# Linters settings
linters-settings:
  # Revive is a fast, configurable, extensible, flexible, and beautiful linter for Go
  revive:
    # Minimal confidence for issues to be reported
    min-confidence: 0.8
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
  
  # Detect bugs, performance and style issues
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - fieldalignment # Too strict for initial development

  # Linter for error handling statements
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true
    # Report about assignment of errors to blank identifier
    check-blank: true

  # Golang static analysis
  staticcheck:
    # Select specific checks to enable or disable
    # By default all checks are enabled
    checks: ["all"]

# Configure specific linters
linters:
  # Only use officially supported linters
  disable-all: true
  enable:
    # Enabled by default
    - errcheck     # Check for unchecked errors
    - govet        # Examines Go source code and reports suspicious constructs
    - ineffassign  # Detects when assignments to existing variables are not used
    - staticcheck  # Go static analysis
    - unused       # Checks for unused constants, variables, functions and types
    
    # Disabled by default but useful for our project
    - revive       # Fast, configurable, extensible linter for Go
    - misspell     # Finds commonly misspelled English words
    - gocyclo      # Computes and checks the cyclomatic complexity of functions
    - dupl         # Detects duplicate fragments of code
    - gosec        # Inspects source code for security problems
    - godot        # Check if comments end in a period
    - unconvert    # Remove unnecessary type conversions
    - whitespace   # Checks whitespace usage

# Issues configuration
issues:
  # Maximum issues count per one linter
  # Default: 50
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  # Default: 3
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - migrations
    - .github
    - scripts/package
  
  # Excluding configuration for specific rules and files
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  # Enable automatic fixing where possible
  fix: true

# Output configuration
output:
  formats:
    text:
      path: stdout
    json:
      path: ./.temp/golangci-lint-report.json
    html:
      path: ./.temp/golangci-lint-report.html
  sort-results: true
  sort-order:
    - linter
    - file
    - severity
