version: 2

project_name: chatlogger-api-go
builds:
  - id: chatlogger
    main: ./cmd/server
    binary: chatlogger-api-go_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0
      - COSIGN_PRIV_KEY={{ if index .Env "COSIGN_PRIVATE_KEY"  }}{{ .Env.COSIGN_PRIVATE_KEY }}{{ else }}cosign.key{{ end }}
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X github.com/kjanat/ChatLogger-API-go/internal/version.Version={{.Version}}
      - -X github.com/kjanat/ChatLogger-API-go/internal/version.BuildTime={{.Date}}
      - -X github.com/kjanat/ChatLogger-API-go/internal/version.GitCommit={{.Commit}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - migrations/*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

# release:
#   disable: true

nfpms:
  - id: chatlogger-api-go
    package_name: "{{.ProjectName}}"
    vendor: kjanat
    homepage: https://github.com/kjanat/ChatLogger-API-go
    maintainer: ChatLogger Maintainers <chatlogger-api-go@kjanat.com>
    description: |-
      Multi-tenant backend API for logging and managing chat sessions.
      Supports authenticated and unauthenticated usage with analytics.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - postgresql
    contents:
      - src: ./migrations/
        dst: /var/lib/chatlogger/migrations
        type: tree
      - src: ./scripts/systemd/chatlogger.service
        dst: /etc/systemd/system/chatlogger.service
        type: config
    scripts:
      postinstall: "./scripts/package/postinstall.sh"
      preremove: "./scripts/package/preremove.sh"

# dockers:
#   - image_templates:
#       - "ghcr.io/kjanat/{{.ProjectName}}:latest"
#       - "ghcr.io/kjanat/{{.ProjectName}}:{{ .Tag }}"
#       - "ghcr.io/kjanat/{{.ProjectName}}:{{ .Tag }}-{{ .Env.GORELEASE_CURRENT_RUN }}"
#       - "ghcr.io/kjanat/{{.ProjectName}}:v{{ .Major }}"
#     dockerfile: Dockerfile

# docker_signs:
#   - id: chatlogger
#     cmd: cosign
#     args:
#       - "sign"
#       - "--key={{ .Env.COSIGN_PRIV_KEY }}"
#       - "${artifact}"
#       - "--yes"
#     artifacts: all
