version: 2

project_name: ChatLogger-API-go
builds:
  - id: server
    main: ./cmd/server
    binary: chatlogger-server
    ldflags: ['-s -w -X "ChatLogger-API-go/internal/version.Version={{.Version}}" -X "ChatLogger-API-go/internal/version.BuildTime={{.Date}}" -X "ChatLogger-API-go/internal/version.GitCommit={{.Commit}}"']
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

  - id: worker
    main: ./cmd/worker
    binary: chatlogger-worker
    ldflags: ['-s -w -X "ChatLogger-API-go/internal/version.Version={{.Version}}" -X "ChatLogger-API-go/internal/version.BuildTime={{.Date}}" -X "ChatLogger-API-go/internal/version.GitCommit={{.Commit}}"']
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - migrations/*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

nfpms:
  - id: ChatLogger-API-go
    package_name: "{{.ProjectName}}"
    vendor: kjanat
    homepage: https://github.com/kjanat/ChatLogger-API-go
    maintainer: ChatLogger Maintainers <chatlogger-api-go@kjanat.com>
    description: |-
      Multi-tenant backend API for logging and managing chat sessions.
      Supports authenticated and unauthenticated usage with analytics.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - postgresql
    contents:
      - src: ./migrations/
        dst: /var/lib/chatlogger/migrations
        type: tree
      - src: ./scripts/systemd/chatlogger.service
        dst: /etc/systemd/system/chatlogger.service
        type: config
    scripts:
      postinstall: "./scripts/package/postinstall.sh"
      preremove: "./scripts/package/preremove.sh"

dockers:
  - image_templates:
    - "ghcr.io/kjanat/chatlogger-api-go:server-latest"
    - "ghcr.io/kjanat/chatlogger-api-go:server-{{.Major}}"
    - "ghcr.io/kjanat/chatlogger-api-go:server-{{.Major}}.{{.Minor}}"
    - "ghcr.io/kjanat/chatlogger-api-go:server-{{.Version}}"
    dockerfile: .github/workflows/docker/Dockerfile.server
    goos: linux
    goarch: amd64
    ids: [server]
  
  - image_templates:
    - "ghcr.io/kjanat/chatlogger-api-go:worker-latest"
    - "ghcr.io/kjanat/chatlogger-api-go:worker-{{.Major}}"
    - "ghcr.io/kjanat/chatlogger-api-go:worker-{{.Major}}.{{.Minor}}"
    - "ghcr.io/kjanat/chatlogger-api-go:worker-{{.Version}}"
    dockerfile: .github/workflows/docker/Dockerfile.worker
    goos: linux
    goarch: amd64
    ids: [worker]

docker_signs:
  - id: chatlogger
    cmd: cosign
    args:
      - "sign"
      - "--key={{ .Env.COSIGN_PRIVATE_KEY }}"
      - "${artifact}"
      - "--yes"
    artifacts: all
