FROM alpine:3.21.3
WORKDIR /app
COPY ChatLogger-API-go-worker* ChatLogger-API-go-worker
ENV GIN_MODE=release
RUN mkdir -p /app/exports
RUN chmod +x /app/ChatLogger-API-go-worker
CMD ["/app/ChatLogger-API-go-worker"]
