# Build Stage
FROM golang AS builder

ARG LD_FLAGS

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Build the server binary for linux
RUN go build \
    -ldflags="${LD_FLAGS}" \
    -o /out/server \
    ./cmd/server

# Final Stage
FROM alpine

WORKDIR /app
ENV GIN_MODE=release
COPY docs /app
COPY --from=builder /out/server /usr/local/bin/chatlogger-server

EXPOSE 8080

ENTRYPOINT [ "chatlogger-server" ]
