# Build Stage
FROM golang AS builder

ARG LD_FLAGS

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Build the worker binary for linux
RUN go build \
    -ldflags="${LD_FLAGS}" \
    -o /out/worker \
    ./cmd/worker

# Final Stage
FROM alpine

WORKDIR /app
ENV GIN_MODE=release
COPY --from=builder /out/worker /usr/local/bin/chatlogger-worker
RUN mkdir -p /app/exports

ENTRYPOINT [ "chatlogger-worker" ]
