name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - kjanat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request! Please [check for existing requests](https://github.com/kjanat/chatlogger-api-go/issues) before submitting. If you find one, feel free to add more information or give a 👍 to the original issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or enhancement you're proposing
      placeholder: Explain the current situation and why this change would be beneficial
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the specific requirements or changes needed
      placeholder: |
        - Requirement 1
        - Requirement 2
        - Requirement 3
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: What criteria need to be met for this feature to be considered complete?
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        - [ ] Relevant documentation is updated
        - [ ] Unit tests are updated/written and passing
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other context, implementation suggestions, or considerations
      placeholder: Add any other relevant information here
