name: Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      created_tag: ${{ steps.create_tag.outputs.created }}
      version: ${{ steps.extract_version.outputs.version }}
      build_time: ${{ steps.extract_version.outputs.build_time }}
      git_commit: ${{ steps.extract_version.outputs.git_commit }}
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version
        id: extract_version
        shell: bash
        run: |
          # Extract version using robust pattern matching with fallback
          VERSION=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go || grep 'Version = ' internal/version/version.go | awk -F'"' '{print $2}')
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          GIT_COMMIT=$(git rev-parse HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "git_commit=$GIT_COMMIT" >> $GITHUB_OUTPUT
          echo "Version: $VERSION, Build time: $BUILD_TIME, Git commit: $GIT_COMMIT"
          echo "Extracted version: $VERSION"

      - name: Create Tag If Needed
        id: create_tag
        run: |
          git fetch --tags
          VERSION=${{ steps.extract_version.outputs.version }}
          GIT_COMMIT=${{ steps.extract_version.outputs.git_commit }}
          CURRENT_COMMIT=$(git rev-parse HEAD)
          
          if [ "$GIT_COMMIT" != "$CURRENT_COMMIT" ]; then
            echo "Error: Extracted commit $GIT_COMMIT does not match the current commit $CURRENT_COMMIT."
            exit 1
          fi
          
          if git tag | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists"
            echo "created=false" >> $GITHUB_OUTPUT
          else
            echo "Creating tag v$VERSION"
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "created=true" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [tag-version]
    permissions:
      contents: read
    if: ${{ always() && (needs.tag-version.result == 'success' || needs.tag-version.result == 'skipped') }}
    strategy:
      fail-fast: false
      matrix:
        scripts:
          - server
          - worker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      # - name: Run Tests
      #   run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Extract Build Info
        id: extract_build_info
        run: |
          echo "Version: ${{ needs.tag-version.outputs.version }}, Build time: ${{ needs.tag-version.outputs.build_time }}, Git commit: ${{ needs.tag-version.outputs.git_commit }}"

      - name: Build Binary ${{ matrix.scripts }}-v${{ needs.tag-version.outputs.version }}
        run: |
          go build -ldflags "-s -w \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.Version=${{ needs.tag-version.outputs.version }} \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.BuildTime=${{ needs.tag-version.outputs.build_time }} \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.GitCommit=${{ needs.tag-version.outputs.git_commit }}" \
            -o dist/chatlogger-api-${{ matrix.scripts }}-v${{ needs.tag-version.outputs.version }}.bin \
            ./cmd/${{ matrix.scripts }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatlogger-api-${{ matrix.scripts }}-${{ needs.tag-version.outputs.version }} #_${{ github.run_id }}
          path: dist/chatlogger-api-${{ matrix.scripts }}-v${{ needs.tag-version.outputs.version }}.bin
          retention-days: 5
          overwrite: true

  release:
    needs: [tag-version]
    if: needs.tag-version.outputs.created_tag == 'true'
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      repo: ${{ github.event.repository.full_name }}
      version: ${{ needs.tag-version.outputs.version }}
      build_time: ${{ needs.tag-version.outputs.build_time }}
      git_commit: ${{ needs.tag-version.outputs.git_commit }}
    secrets:
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
