name: Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      created_tag: ${{ steps.create_tag.outputs.created }}
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version
        id: extract_version
        shell: bash
        run: |
          # Extract version using robust pattern matching with fallback
          VERSION=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go || grep 'Version = ' internal/version/version.go | awk -F'"' '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Create Tag If Needed
        id: create_tag
        run: |
          git fetch --tags
          if git tag | grep -q "^v${{ steps.extract_version.outputs.version }}$"; then
            echo "Tag v${{ steps.extract_version.outputs.version }} already exists"
            echo "created=false" >> $GITHUB_OUTPUT
          else
            echo "Creating tag v${{ steps.extract_version.outputs.version }}"
            git tag "v${{ steps.extract_version.outputs.version }}"
            git push origin "v${{ steps.extract_version.outputs.version }}"
            echo "created=true" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [tag-version]
    permissions:
      contents: read
    if: ${{ always() && (needs.tag-version.result == 'success' || needs.tag-version.result == 'skipped') }}
    strategy:
      fail-fast: false
      matrix:
        scripts:
          - server
          - worker
    outputs:
      version: ${{ steps.extract_build_info.outputs.version }}
      build_time: ${{ steps.extract_build_info.outputs.build_time }}
      git_commit: ${{ steps.extract_build_info.outputs.git_commit }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      # - name: Run Tests
      #   run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Extract Build Info
        id: extract_build_info
        run: |
          VERSION=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go || grep 'Version = ' internal/version/version.go | awk -F'"' '{print $2}')
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          GIT_COMMIT=$(git rev-parse HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "git_commit=$GIT_COMMIT" >> $GITHUB_OUTPUT
          echo "Version: $VERSION, Build time: $BUILD_TIME, Git commit: $GIT_COMMIT"

      - name: Build Binary ${{ matrix.scripts }}-v${{ steps.extract_build_info.outputs.version }}
        run: |
          go build -ldflags "-s -w \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.Version=${{ steps.extract_build_info.outputs.version }} \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.BuildTime=${{ steps.extract_build_info.outputs.build_time }} \
            -X github.com/kjanat/ChatLogger-API-go/internal/version.GitCommit=${{ steps.extract_build_info.outputs.git_commit }}" \
            -o chatlogger-api-${{ matrix.scripts }}-${{ steps.extract_build_info.outputs.version }} \
            ./cmd/${{ matrix.scripts }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatlogger-api_${{ matrix.scripts }}_linux-amd64_${{ github.run_id }}
          path: chatlogger-api-${{ matrix.scripts }}-${{ steps.extract_build_info.outputs.version }}
          retention-days: 5

  release:
    name: Trigger Release Workflow
    needs: [tag-version, build]
    if: needs.tag-version.outputs.created_tag == 'true'
    uses: kjanat/ChatLogger-API-go/.github/workflows/release.yml@master
    with:
      version: ${{ needs.build.outputs.version }}
      build_time: ${{ needs.build.outputs.build_time }}
      git_commit: ${{ needs.build.outputs.git_commit }}
