name: Tag Versioning

on:
  push:
    branches:
      - main
      - master

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Extract version directly from version.go
      - name: Extract Version from version.go
        id: get_version
        run: |
          VERSION=$(grep 'Version = ' internal/version/version.go | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Fetch existing tags
      - name: Fetch All Tags
        run: git fetch --tags

      # Create or update tag
      - name: Create or Update Tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          # Check if the tag exists
          if git tag | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists. Deleting and recreating it..."
            git tag -d "v$VERSION"
            git push origin :refs/tags/v$VERSION || echo "Remote tag doesn't exist, continuing..."
          else
            echo "Tag v$VERSION does not exist. Creating it..."
          fi
          
          # Create and push the tag
          git tag "v$VERSION"
          git push origin "v$VERSION"
