name: Version Management

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Execute version script
        run: |
          chmod +x ./scripts/version.sh
          ./scripts/version.sh ${{ github.event.inputs.version_type }}

      - name: Commit and push changes
        run: |
          new_version=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go)
          git config user.email "${{ secrets.ACTIONS_EMAIL }}"
          git config user.name "${{ secrets.ACTIONS_USERNAME }}"
          git config user.signingkey "${{ steps.import_gpg.outputs.fingerprint }}"
          git config commit.gpgsign true
          git config tag.gpgsign true
          git add internal/version/version.go
          git commit -S -m "Bump version to $new_version"
          git push
          echo "Version bumped to $new_version"

      - name: Create and push tag
        run: |
          VERSION=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go)
          git tag -s "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
          echo "Created and pushed tag v$VERSION"
