name: Version Management

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Execute version script
        run: |
          ./scripts/version.sh ${{ github.event.inputs.version_type }}

      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add internal/version/version.go
          git commit -m "Bump version to $(grep -oP 'Version = "\K[^"]+' internal/version/version.go)"
          git push

      - name: Create and push tag
        run: |
          VERSION=$(grep -oP 'Version = "\K[^"]+' internal/version/version.go)
          git tag "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
